import { StatusCodes } from 'http-status-codes';

const {
  INTERNAL_SERVER_ERROR,
  OK,
  LENGTH_REQUIRED,
  UNPROCESSABLE_ENTITY,
  NOT_ACCEPTABLE,
  CONFLICT,
  UNAUTHORIZED,
  NOT_FOUND,
  CREATED,
  ACCEPTED,
  BAD_REQUEST,
} = StatusCodes;

export {
  INTERNAL_SERVER_ERROR,
  OK,
  UNPROCESSABLE_ENTITY,
  LENGTH_REQUIRED,
  NOT_ACCEPTABLE,
  CONFLICT,
  UNAUTHORIZED,
  NOT_FOUND,
  CREATED,
  ACCEPTED,
  BAD_REQUEST,
};
